name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a
        run: echo "Hello world"
      - name: multiline
        run: |
          node -v
  run-windows-command:
    - name: Dir powershell
      run: Get-Location
